version: "3.7"
services:
  postgres-node:
    image: postgres:13
    env_file:
      - postgres.env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
volumes:
  pg_data:
