version: "3.8"

services:
  billing_scheduler:
    build: scheduler
    container_name: billing_scheduler
    command: python3 main.py
    depends_on:
      - billing_db
    restart: always
    env_file:
      - scheduler/.env.prod

  billing-admin-panel:
    build: admin_panel
    container_name: billing-admin-panel
    command: gunicorn config.wsgi:application --bind 0.0.0.0:9044 -w1
    env_file:
      - admin_panel/config/settings/.env.prod
    depends_on:
      - billing_db
    volumes:
      - static_volume:/usr/src/admin_panel/config/static

  billing_db:
    image: postgres
    container_name: billing_db
    volumes:
      - billing_db_data:/var/lib/postgresql/data/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init_schema.sql
    env_file:
      - db/.env.prod
    restart: always

  billing_api:
    build: billing_api
    container_name: billing_api
    command: python3 src/main.py
    expose:
      - 8787
    depends_on:
      - billing_db

  billing_nginx:
    build: nginx
    container_name: billing_nginx
    ports:
      - 9044:9044
      - 8787:8787
    depends_on:
      - billing-admin-panel
      - billing_api
    volumes:
      - billing_nginx_logs:/var/log/nginx/
      - static_volume:/usr/src/admin_panel/config/static
    restart: always


volumes:
  billing_db_data:
  static_volume:
  billing_nginx_logs:
    name: billing_nginx_logs

#networks:
#  default:
#    external:
#      name: auth_sprint_2_dotnetwork
