-- upgrade --
ALTER TABLE "orders" ALTER COLUMN "payment_amount" TYPE DECIMAL(10,2) USING "payment_amount"::DECIMAL(10,2);
ALTER TABLE "orders" ALTER COLUMN "payment_amount" TYPE DECIMAL(10,2) USING "payment_amount"::DECIMAL(10,2);
ALTER TABLE "orders" ALTER COLUMN "payment_amount" TYPE DECIMAL(10,2) USING "payment_amount"::DECIMAL(10,2);
ALTER TABLE "orders" ALTER COLUMN "payment_amount" TYPE DECIMAL(10,2) USING "payment_amount"::DECIMAL(10,2);
ALTER TABLE "products" ALTER COLUMN "price" TYPE DECIMAL(10,2) USING "price"::DECIMAL(10,2);
ALTER TABLE "products" ALTER COLUMN "price" TYPE DECIMAL(10,2) USING "price"::DECIMAL(10,2);
ALTER TABLE "products" ALTER COLUMN "price" TYPE DECIMAL(10,2) USING "price"::DECIMAL(10,2);
ALTER TABLE "products" ALTER COLUMN "price" TYPE DECIMAL(10,2) USING "price"::DECIMAL(10,2);
-- downgrade --
ALTER TABLE "orders" ALTER COLUMN "payment_amount" TYPE DOUBLE PRECISION USING "payment_amount"::DOUBLE PRECISION;
ALTER TABLE "orders" ALTER COLUMN "payment_amount" TYPE DOUBLE PRECISION USING "payment_amount"::DOUBLE PRECISION;
ALTER TABLE "orders" ALTER COLUMN "payment_amount" TYPE DOUBLE PRECISION USING "payment_amount"::DOUBLE PRECISION;
ALTER TABLE "orders" ALTER COLUMN "payment_amount" TYPE DOUBLE PRECISION USING "payment_amount"::DOUBLE PRECISION;
ALTER TABLE "products" ALTER COLUMN "price" TYPE DOUBLE PRECISION USING "price"::DOUBLE PRECISION;
ALTER TABLE "products" ALTER COLUMN "price" TYPE DOUBLE PRECISION USING "price"::DOUBLE PRECISION;
ALTER TABLE "products" ALTER COLUMN "price" TYPE DOUBLE PRECISION USING "price"::DOUBLE PRECISION;
ALTER TABLE "products" ALTER COLUMN "price" TYPE DOUBLE PRECISION USING "price"::DOUBLE PRECISION;
